module.exports.descriptors = [
    'Himalayan',
    'Royal',
    'Mystic',
    'Tiger',
    'Monsoon',
    'Desert',
    'Valley',
    'Sacred',
    'Spice',
    'Tea Garden',
    'Jungle',
    'Banyan',
    'Sunrise',
    'Golden',
    'Emerald',
    'Vedic',
    'Misty',
    'Snowy',
    'Riverside',
    'Serene'
]

module.exports.places = [
    'Camp',
    'Retreat',
    'Basecamp',
    'Ghat',
    'Sanctuary',
    'Outdoors',
    'Hills',
    'Oasis',
    'Meadows',
    'Woods',
    'Eco Resort',
    'Safari',
    'Homestay',
    'Tents',
    'Valley',
    'Village'
]